# Generated by Django 6.0 on 2026-01-13 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_item_wholesale_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='wholesale_price',
        ),
        migrations.AddField(
            model_name='repairticket',
            name='customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_type',
            field=models.CharField(default='Retail', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='unit_price_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='repairticket',
            name='payment_method',
            field=models.CharField(default='Cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='repairticket',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('In Progress', 'In Progress'), ('Done', 'Done'), ('Delivered', 'Delivered')], default='Received', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(default='Cash', max_length=20),
        ),
        migrations.CreateModel(
            name='RepairPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item')),
                ('repair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='api.repairticket')),
            ],
        ),
    ]
