# Generated by Django 6.0 on 2026-01-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_item_cost_price_remove_item_wholesale_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='unit_price_snapshot',
            new_name='unit_price',
        ),
        migrations.AddField(
            model_name='item',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='repairticket',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Fonepay', 'Fonepay'), ('Bank', 'Bank Transfer'), ('Credit', 'Credit')], default='Cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Fonepay', 'Fonepay'), ('Bank', 'Bank Transfer'), ('Credit', 'Credit')], default='Cash', max_length=20),
        ),
    ]
