# Generated by Django 6.0 on 2025-12-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='imei_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
