# Generated by Django 6.0 on 2026-01-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_item_cost_price_sale_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
